export const statesList = [
  { id: 1, name: "Andhra Pradesh", slug: "andhra-pradesh" },
  { id: 2, name: "Arunachal Pradesh", slug: "arunachal-pradesh" },
  { id: 3, name: "Assam", slug: "assam" },
  { id: 4, name: "Bihar", slug: "bihar" },
  { id: 5, name: "Chattisgarh", slug: "chattisgarh" },
  { id: 6, name: "Goa", slug: "goa" },
  { id: 7, name: "Gujarat", slug: "gujarat" },
  { id: 8, name: "Haryana", slug: "haryana" },
  { id: 9, name: "Himachal Pradesh", slug: "himachal-pradesh" },
  { id: 10, name: "Jharkhand", slug: "jharkhand" },
  { id: 11, name: "Karnataka", slug: "karnataka" },
  { id: 12, name: "Kerala", slug: "kerala" },
  { id: 13, name: "Madhya Pradesh", slug: "madhya-pradesh" },
  { id: 14, name: "Maharashtra", slug: "maharashtra" },
  { id: 15, name: "Manipur", slug: "manipur" },
  { id: 16, name: "Meghalaya", slug: "meghalaya" },
  { id: 17, name: "Mizoram", slug: "mizoram" },
  { id: 18, name: "Nagaland", slug: "nagaland" },
  { id: 19, name: "Odisha", slug: "odisha" },
  { id: 20, name: "Punjab", slug: "punjab" },
  { id: 21, name: "Rajasthan", slug: "rajasthan" },
  { id: 22, name: "Sikkim", slug: "sikkim" },
  { id: 23, name: "Tamil Nadu", slug: "tamil-nadu" },
  { id: 24, name: "Telangana", slug: "telangana" },
  { id: 25, name: "Tripura", slug: "tripura" },
  { id: 26, name: "Uttar Pradesh", slug: "uttar-pradesh" },
  { id: 27, name: "Uttarakhand", slug: "uttarakhand" },
  { id: 28, name: "West Bengal", slug: "west-bengal" },
];